### PR TITLE
Use local configurations from core repo.

### PR DESCRIPTION
**Pull request by style95**
This is to apply changes in the core repo automatically.

### CODE REVIEW

**Review by rabbah — APPROVED** [review]

**Comment by dgrove-oss** [comment]
Hi.  I thought about doing this earlier this week, but I think we need to remove swift 4.1 first.  We have a local group_vars/all in this project partially to get a swift:4.1 kind (which is no longer in the main repo).

**Comment by dgrove-oss** [comment]
Remove swift 4.1 might be simplified by merging #126 first.

**Comment by dgrove-oss** [comment]
#135 is an attempt to get runtime-swift to use the same build/test pattern as our other runtime repos.  Assuming we can do that, we won't need this change

**Comment by dgrove-oss** [comment]
Sigh #135 won't work because testing the Swift SDK requires a full OpenWhisk deployment (unlike every other openwhisk-runtime).  Reopening this and will adjust to account for the removal of swift 4.1

**Comment by dgrove-oss** [comment]
picked up the changes from here into #137 so I could hack on them locally...will hopefully get them working and them commit

**Pull request closed without merging**
