### PR TITLE
Fix build by adapting akka versions

### PR DESCRIPTION
**Pull request by mhenke1**
Fix taken from https://github.com/apache/openwhisk-runtime-ruby/pull/61

### CODE REVIEW

**Review by dgrove-oss — COMMENTED** [review]
@rabbah  -- should we propagate this block across all the runtimes or does https://github.com/apache/openwhisk/pull/5133 and https://github.com/apache/openwhisk/pull/5130/files simplify things?

**Comment by rabbah** [comment]
Removing Mesos and bumping the akka kube management will reduce the change set to just 2 pinned libraries. Mesos was OK in Circle CI but the akka kube bump failed and I didn't investigate it. We can at least merge Mesos - I need to set aside some time to look into the other issue, I can't do it today.

**Comment by dgrove-oss** [comment]
ok.  I merged apache/openwhisk#5133.  @mhenke1 I'll approve this in case it is urgently needed, but if we can stall for few days to avoid needing to do a separate PR to simplify later it might be better.

**Review by dgrove-oss — APPROVED** [review]
Approved in case fix is urgently needed;  if possible would be nice to delay until we clean up the upstream to reduce the number of pinned libs

**Comment by mhenke1** [comment]
@dgrove-oss I am fine with waiting some more days. 
It would be great if the cleanup and the fixing of the runtimes build could be finished until end of month.

**Comment by dgrove-oss** [comment]
Merged so we can unblock #140

**Pull request merged**
